version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080"
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"